[build]
  command = "yarn install && yarn build"
  publish = "build"

[context.production.environment]
  NODE_VERSION = "20"

[[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = "frame-src 'self' https://www.youtube.com"